# Generated by Django 3.1.3 on 2021-01-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkash_payment', '0002_bkash_payment_payloads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bkash_payment_payloads',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
