version: '3'

services: 
  app:
    build: 
      context: .
    volumes:
      - static_data:/vol/web
    environment:
      - SECRET_KEY=sampleSecretKey
      - ALLOWED_HOSTS=127.0.0.1,localhost,payment.bracnet.net,202.168.232.8
      - DB_HOST=db
      - DB_NAME=bracnet_payment_api
      - DB_USER=faz13
      - DB_PASS=faz13
    depends_on: 
      - db
  db:
    image: mariadb:10.5.8
    environment:
      MYSQL_ROOT_PASSWORD: root@123
      MYSQL_DATABASE: bracnet_payment_api
      MYSQL_USER: faz13
      MYSQL_PASSWORD: faz13
    volumes: 
      # - ./db/data:/var/lib/mysql
      - ./db/test_permission.sql:/docker-entrypoint-initdb.d/test_permission.sql
  
  nginx:
    image: nginx:latest
    container_name: myproject_nginx-container
    volumes:
      - ./proxy:/etc/nginx/conf.d
      - static_data:/vol/static
    depends_on:
      - nginx-proxy # <-- NEW SECTION
      - app
    environment: # <-- NEW SECTION
      - VIRTUAL_HOST=payment.bracnet.net
      - LETSENCRYPT_HOST=payment.bracnet.net
      - LETSENCRYPT_EMAIL=fazlul.haque@bracmail.net

  nginx-proxy: # <-- NEW SECTION
    image: jwilder/nginx-proxy
    container_name: payment_nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "/etc/nginx/conf.d"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "./volumes/proxy/certs:/etc/nginx/certs"
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"

  letsencrypt-companion: # <-- NEW SECTION
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: payment_letsencrypt-companion-container
    volumes_from:
      - nginx-proxy
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./volumes/proxy/certs:/etc/nginx/certs:rw"
  # proxy:
  #   build:
  #     context: ./proxy
  #   volumes: 
  #     - static_data:/vol/static
  #   ports: 
  #     - "8080:8080"
  #   depends_on: 
  #     - app
volumes: 
 static_data: