version: '3'

services:
  nginx: 
    restart: always
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - static_volume:/django_static
      - ./docker/nginx/production:/etc/nginx/conf.d
      - ./docker/nginx/certbot/conf:/etc/letsencrypt
      - ./docker/nginx/certbot/www:/var/www/certbot
    depends_on: 
      - app
  certbot:
    image: certbot/certbot
    restart: always
    volumes:
      - ./docker/nginx/certbot/conf:/etc/letsencrypt
      - ./docker/nginx/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"       
  app:
    restart: always
    build:
      context: .
    entrypoint: /scripts/entrypoint.sh
    volumes:
      - static_volume:/django_static
    expose:
      - 8000
    depends_on: 
      - db
  db:
    image: mariadb:10.5.8
    environment:
      MYSQL_ROOT_PASSWORD: root@123
      MYSQL_DATABASE: bracnet_payment_api
      MYSQL_USER: faz13
      MYSQL_PASSWORD: faz13
    volumes: 
      # - ./db/data:/var/lib/mysql
      - ./db/test_permission.sql:/docker-entrypoint-initdb.d/test_permission.sql      

volumes:
    static_volume: 
