# Generated by Django 3.1.3 on 2020-11-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SslcommerzPaymentInitialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tran_id', models.UUIDField(db_index=True, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('emi_option', models.BooleanField(default=False)),
                ('cus_name', models.CharField(max_length=200)),
                ('cus_phone', models.CharField(max_length=20)),
                ('cus_email', models.EmailField(max_length=255)),
                ('cus_add1', models.TextField(default=None, null=True)),
                ('cus_city', models.CharField(default=None, max_length=40, null=True)),
                ('cus_country', models.CharField(default=None, max_length=50, null=True)),
                ('shipping_method', models.CharField(choices=[('YES', 'YES'), ('AIR', 'AIR'), ('OTHERS', 'OTHERS'), ('COURIER', 'COURIER'), ('NO', 'NO'), ('TRUCK', 'TRUCK'), ('SHIP', 'SHIP')], max_length=20)),
                ('num_of_item', models.IntegerField()),
                ('product_name', models.CharField(max_length=50)),
                ('product_category', models.CharField(max_length=50)),
                ('product_profile', models.CharField(choices=[('travel-vertical', 'travel-vertical'), ('general', 'general'), ('physical-goods', 'physical-goods'), ('telecom-vertical', 'telecom-vertical'), ('airline-tickets', 'airline-tickets'), ('non-physical-goods', 'non-physical-goods')], max_length=50)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
