# Generated by Django 3.1.3 on 2020-11-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sslcommerz_payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sslcommerzpaymentinitialization',
            name='product_profile',
            field=models.CharField(choices=[('telecom-vertical', 'telecom-vertical'), ('physical-goods', 'physical-goods'), ('non-physical-goods', 'non-physical-goods'), ('airline-tickets', 'airline-tickets'), ('general', 'general'), ('travel-vertical', 'travel-vertical')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sslcommerzpaymentinitialization',
            name='shipping_method',
            field=models.CharField(choices=[('SHIP', 'SHIP'), ('YES', 'YES'), ('OTHERS', 'OTHERS'), ('AIR', 'AIR'), ('TRUCK', 'TRUCK'), ('NO', 'NO'), ('COURIER', 'COURIER')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sslcommerzpaymentinitialization',
            name='tran_id',
            field=models.UUIDField(db_index=True, default='bracnet_sslc_<function uuid4 at 0x037D21D8>', unique=True),
        ),
    ]
