# Generated by Django 3.1.3 on 2020-12-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sslcommerz_payment', '0003_auto_20201125_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='SslcommerzPaymentInitializationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tran_id', models.UUIDField(db_index=True, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('emi_option', models.BooleanField(default=False)),
                ('cus_name', models.CharField(max_length=200)),
                ('cus_phone', models.CharField(max_length=20)),
                ('cus_email', models.EmailField(max_length=255)),
                ('cus_add1', models.TextField(default=None, null=True)),
                ('cus_city', models.CharField(default=None, max_length=40, null=True)),
                ('cus_country', models.CharField(default=None, max_length=50, null=True)),
                ('shipping_method', models.CharField(choices=[('YES', 'YES'), ('SHIP', 'SHIP'), ('NO', 'NO'), ('COURIER', 'COURIER'), ('TRUCK', 'TRUCK'), ('OTHERS', 'OTHERS'), ('AIR', 'AIR')], max_length=20)),
                ('num_of_item', models.IntegerField()),
                ('product_name', models.CharField(max_length=50)),
                ('product_category', models.CharField(max_length=50)),
                ('product_profile', models.CharField(choices=[('telecom-vertical', 'telecom-vertical'), ('travel-vertical', 'travel-vertical'), ('general', 'general'), ('airline-tickets', 'airline-tickets'), ('physical-goods', 'physical-goods'), ('non-physical-goods', 'non-physical-goods')], max_length=50)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default=None, max_length=15)),
                ('failed_reason', models.TextField(default=None, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SslcommerzPaymentValidateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tran_id', models.UUIDField(db_index=True, unique=True)),
                ('val_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('card_type', models.CharField(max_length=255)),
                ('store_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('card_no', models.CharField(max_length=16)),
                ('bank_tran_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('UNATTEMPTED', 'UNATTEMPTED'), ('FAILED', 'FAILED'), ('CANCELLED', 'CANCELLED'), ('VALID', 'VALID'), ('EXPIRED', 'EXPIRED')], max_length=50)),
                ('tran_date', models.DateTimeField()),
                ('currency', models.CharField(max_length=3)),
                ('card_issuer', models.CharField(max_length=50)),
                ('card_brand', models.CharField(choices=[('IB', 'IB'), ('MOBILE BANKING', 'MOBILE BANKING'), ('MASTER', 'MASTER'), ('AMEX', 'AMEX'), ('VISA', 'VISA')], max_length=50)),
                ('card_issuer_country', models.CharField(max_length=50)),
                ('card_issuer_country_code', models.CharField(max_length=2)),
                ('store_id', models.CharField(max_length=50)),
                ('verify_sign', models.CharField(max_length=255)),
                ('verify_key', models.CharField(max_length=255)),
                ('currency_type', models.CharField(max_length=3)),
                ('currency_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='SslcommerzPaymentInitialization',
        ),
    ]
