# Generated by Django 3.1.3 on 2020-12-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sslcommerz_payment', '0004_auto_20201201_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sslcommerzpaymentinitializationmodel',
            name='product_profile',
            field=models.CharField(choices=[('telecom-vertical', 'telecom-vertical'), ('physical-goods', 'physical-goods'), ('general', 'general'), ('non-physical-goods', 'non-physical-goods'), ('airline-tickets', 'airline-tickets'), ('travel-vertical', 'travel-vertical')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sslcommerzpaymentinitializationmodel',
            name='shipping_method',
            field=models.CharField(choices=[('AIR', 'AIR'), ('YES', 'YES'), ('TRUCK', 'TRUCK'), ('SHIP', 'SHIP'), ('NO', 'NO'), ('COURIER', 'COURIER'), ('OTHERS', 'OTHERS')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sslcommerzpaymentvalidatemodel',
            name='card_brand',
            field=models.CharField(choices=[('MOBILE BANKING', 'MOBILE BANKING'), ('IB', 'IB'), ('VISA', 'VISA'), ('AMEX', 'AMEX'), ('MASTER', 'MASTER')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sslcommerzpaymentvalidatemodel',
            name='status',
            field=models.CharField(choices=[('VALID', 'VALID'), ('UNATTEMPTED', 'UNATTEMPTED'), ('EXPIRED', 'EXPIRED'), ('CANCELLED', 'CANCELLED'), ('FAILED', 'FAILED')], max_length=50),
        ),
    ]
