# Generated by Django 3.1.3 on 2020-12-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sslcommerz_payment', '0005_auto_20201201_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sslcommerzpaymentinitializationmodel',
            name='product_profile',
            field=models.CharField(choices=[('telecom-vertical', 'telecom-vertical'), ('non-physical-goods', 'non-physical-goods'), ('travel-vertical', 'travel-vertical'), ('airline-tickets', 'airline-tickets'), ('general', 'general'), ('physical-goods', 'physical-goods')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sslcommerzpaymentinitializationmodel',
            name='shipping_method',
            field=models.CharField(choices=[('NO', 'NO'), ('AIR', 'AIR'), ('YES', 'YES'), ('SHIP', 'SHIP'), ('TRUCK', 'TRUCK'), ('OTHERS', 'OTHERS'), ('COURIER', 'COURIER')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sslcommerzpaymentvalidatemodel',
            name='card_brand',
            field=models.CharField(choices=[('MASTER', 'MASTER'), ('IB', 'IB'), ('AMEX', 'AMEX'), ('VISA', 'VISA'), ('MOBILE BANKING', 'MOBILE BANKING')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sslcommerzpaymentvalidatemodel',
            name='status',
            field=models.CharField(choices=[('FAILED', 'FAILED'), ('EXPIRED', 'EXPIRED'), ('CANCELLED', 'CANCELLED'), ('UNATTEMPTED', 'UNATTEMPTED'), ('VALID', 'VALID')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sslcommerzpaymentvalidatemodel',
            name='verify_key',
            field=models.TextField(),
        ),
    ]
