# Generated by Django 3.1.3 on 2020-12-03 11:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sslcommerz_payment', '0007_auto_20201203_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sslcommerzpaymentinitializationmodel',
            name='product_profile',
            field=models.CharField(choices=[('physical-goods', 'physical-goods'), ('general', 'general'), ('airline-tickets', 'airline-tickets'), ('telecom-vertical', 'telecom-vertical'), ('travel-vertical', 'travel-vertical'), ('non-physical-goods', 'non-physical-goods')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sslcommerzpaymentinitializationmodel',
            name='shipping_method',
            field=models.CharField(choices=[('TRUCK', 'TRUCK'), ('YES', 'YES'), ('AIR', 'AIR'), ('COURIER', 'COURIER'), ('NO', 'NO'), ('OTHERS', 'OTHERS'), ('SHIP', 'SHIP')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sslcommerzpaymentvalidatemodel',
            name='card_brand',
            field=models.CharField(choices=[('MOBILE BANKING', 'MOBILE BANKING'), ('IB', 'IB'), ('MASTER', 'MASTER'), ('VISA', 'VISA'), ('AMEX', 'AMEX')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sslcommerzpaymentvalidatemodel',
            name='emi_description',
            field=models.TextField(default='no description'),
        ),
        migrations.AlterField(
            model_name='sslcommerzpaymentvalidatemodel',
            name='tran_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 3, 11, 43, 59, 625179, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sslcommerzpaymentvalidatemodel',
            name='validated_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 3, 11, 43, 59, 625506, tzinfo=utc)),
        ),
    ]
