# Generated by Django 3.1.3 on 2020-12-03 12:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sslcommerz_payment', '0011_auto_20201203_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sslcommerzpaymentinitializationmodel',
            name='product_profile',
            field=models.CharField(choices=[('non-physical-goods', 'non-physical-goods'), ('general', 'general'), ('telecom-vertical', 'telecom-vertical'), ('travel-vertical', 'travel-vertical'), ('airline-tickets', 'airline-tickets'), ('physical-goods', 'physical-goods')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sslcommerzpaymentinitializationmodel',
            name='shipping_method',
            field=models.CharField(choices=[('NO', 'NO'), ('YES', 'YES'), ('TRUCK', 'TRUCK'), ('SHIP', 'SHIP'), ('OTHERS', 'OTHERS'), ('AIR', 'AIR'), ('COURIER', 'COURIER')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sslcommerzpaymentvalidatemodel',
            name='account_details',
            field=models.CharField(default='No description', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sslcommerzpaymentvalidatemodel',
            name='card_brand',
            field=models.CharField(choices=[('VISA', 'VISA'), ('AMEX', 'AMEX'), ('IB', 'IB'), ('MASTER', 'MASTER'), ('MOBILE BANKING', 'MOBILE BANKING')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sslcommerzpaymentvalidatemodel',
            name='tran_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 3, 12, 3, 36, 384393, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sslcommerzpaymentvalidatemodel',
            name='validated_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 3, 12, 3, 36, 384678, tzinfo=utc)),
        ),
    ]
