# Generated by Django 3.1.3 on 2020-12-03 12:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sslcommerz_payment', '0012_auto_20201203_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sslcommerzpaymentvalidatemodel',
            name='account_details',
        ),
        migrations.AlterField(
            model_name='sslcommerzpaymentinitializationmodel',
            name='product_profile',
            field=models.CharField(choices=[('airline-tickets', 'airline-tickets'), ('physical-goods', 'physical-goods'), ('travel-vertical', 'travel-vertical'), ('telecom-vertical', 'telecom-vertical'), ('non-physical-goods', 'non-physical-goods'), ('general', 'general')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sslcommerzpaymentinitializationmodel',
            name='shipping_method',
            field=models.CharField(choices=[('TRUCK', 'TRUCK'), ('SHIP', 'SHIP'), ('YES', 'YES'), ('AIR', 'AIR'), ('NO', 'NO'), ('OTHERS', 'OTHERS'), ('COURIER', 'COURIER')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sslcommerzpaymentvalidatemodel',
            name='card_brand',
            field=models.CharField(choices=[('MASTER', 'MASTER'), ('IB', 'IB'), ('AMEX', 'AMEX'), ('MOBILE BANKING', 'MOBILE BANKING'), ('VISA', 'VISA')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sslcommerzpaymentvalidatemodel',
            name='tran_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 3, 12, 4, 40, 834151, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sslcommerzpaymentvalidatemodel',
            name='validated_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 3, 12, 4, 40, 834474, tzinfo=utc)),
        ),
    ]
