# Generated by Django 3.1.3 on 2020-12-06 11:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sslcommerz_payment', '0014_auto_20201206_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sslcommerzpaymentinitializationmodel',
            name='product_profile',
            field=models.CharField(choices=[('travel-vertical', 'travel-vertical'), ('non-physical-goods', 'non-physical-goods'), ('physical-goods', 'physical-goods'), ('airline-tickets', 'airline-tickets'), ('telecom-vertical', 'telecom-vertical'), ('general', 'general')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sslcommerzpaymentinitializationmodel',
            name='shipping_method',
            field=models.CharField(choices=[('SHIP', 'SHIP'), ('COURIER', 'COURIER'), ('YES', 'YES'), ('NO', 'NO'), ('TRUCK', 'TRUCK'), ('OTHERS', 'OTHERS'), ('AIR', 'AIR')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sslcommerzpaymentvalidatemodel',
            name='tran_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 6, 11, 17, 41, 614015, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sslcommerzpaymentvalidatemodel',
            name='val_id',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sslcommerzpaymentvalidatemodel',
            name='validated_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 6, 11, 17, 41, 614289, tzinfo=utc)),
        ),
    ]
