# Generated by Django 3.1.3 on 2020-12-07 07:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sslcommerz_payment', '0015_auto_20201206_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sslcommerzpaymentinitializationmodel',
            name='product_profile',
            field=models.CharField(choices=[('travel-vertical', 'travel-vertical'), ('telecom-vertical', 'telecom-vertical'), ('airline-tickets', 'airline-tickets'), ('general', 'general'), ('physical-goods', 'physical-goods'), ('non-physical-goods', 'non-physical-goods')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sslcommerzpaymentinitializationmodel',
            name='shipping_method',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO'), ('COURIER', 'COURIER'), ('AIR', 'AIR'), ('TRUCK', 'TRUCK'), ('OTHERS', 'OTHERS'), ('SHIP', 'SHIP')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sslcommerzpaymentvalidatemodel',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sslcommerzpaymentvalidatemodel',
            name='tran_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 7, 7, 13, 23, 44461, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sslcommerzpaymentvalidatemodel',
            name='validated_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 7, 7, 13, 23, 44849, tzinfo=utc)),
        ),
    ]
