# Generated by Django 3.1.3 on 2020-12-07 08:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sslcommerz_payment', '0016_auto_20201207_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sslcommerzpaymentinitializationmodel',
            name='product_profile',
            field=models.CharField(choices=[('non-physical-goods', 'non-physical-goods'), ('travel-vertical', 'travel-vertical'), ('airline-tickets', 'airline-tickets'), ('telecom-vertical', 'telecom-vertical'), ('physical-goods', 'physical-goods'), ('general', 'general')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sslcommerzpaymentinitializationmodel',
            name='shipping_method',
            field=models.CharField(choices=[('COURIER', 'COURIER'), ('NO', 'NO'), ('SHIP', 'SHIP'), ('TRUCK', 'TRUCK'), ('OTHERS', 'OTHERS'), ('AIR', 'AIR'), ('YES', 'YES')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sslcommerzpaymentvalidatemodel',
            name='card_brand',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sslcommerzpaymentvalidatemodel',
            name='card_issuer_country',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sslcommerzpaymentvalidatemodel',
            name='card_issuer_country_code',
            field=models.CharField(default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='sslcommerzpaymentvalidatemodel',
            name='emi_description',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sslcommerzpaymentvalidatemodel',
            name='tran_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 7, 8, 5, 31, 814488, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sslcommerzpaymentvalidatemodel',
            name='validated_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 7, 8, 5, 31, 814829, tzinfo=utc), null=True),
        ),
    ]
