# Generated by Django 3.1.3 on 2020-12-07 08:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sslcommerz_payment', '0018_auto_20201207_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sslcommerzpaymentinitializationmodel',
            name='product_profile',
            field=models.CharField(choices=[('travel-vertical', 'travel-vertical'), ('non-physical-goods', 'non-physical-goods'), ('physical-goods', 'physical-goods'), ('airline-tickets', 'airline-tickets'), ('telecom-vertical', 'telecom-vertical'), ('general', 'general')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sslcommerzpaymentinitializationmodel',
            name='shipping_method',
            field=models.CharField(choices=[('YES', 'YES'), ('SHIP', 'SHIP'), ('AIR', 'AIR'), ('OTHERS', 'OTHERS'), ('TRUCK', 'TRUCK'), ('COURIER', 'COURIER'), ('NO', 'NO')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sslcommerzpaymentvalidatemodel',
            name='currency_type',
            field=models.CharField(default=None, max_length=3, null=None),
        ),
        migrations.AlterField(
            model_name='sslcommerzpaymentvalidatemodel',
            name='tran_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 7, 8, 11, 24, 228318, tzinfo=utc)),
        ),
    ]
