# Generated by Django 3.1.3 on 2020-12-07 09:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sslcommerz_payment', '0019_auto_20201207_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='sslcommerzpaymentinitializationmodel',
            name='cancel_url',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sslcommerzpaymentinitializationmodel',
            name='fail_url',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sslcommerzpaymentinitializationmodel',
            name='success_url',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sslcommerzpaymentinitializationmodel',
            name='product_profile',
            field=models.CharField(choices=[('travel-vertical', 'travel-vertical'), ('airline-tickets', 'airline-tickets'), ('non-physical-goods', 'non-physical-goods'), ('general', 'general'), ('physical-goods', 'physical-goods'), ('telecom-vertical', 'telecom-vertical')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sslcommerzpaymentinitializationmodel',
            name='shipping_method',
            field=models.CharField(choices=[('COURIER', 'COURIER'), ('SHIP', 'SHIP'), ('YES', 'YES'), ('NO', 'NO'), ('TRUCK', 'TRUCK'), ('OTHERS', 'OTHERS'), ('AIR', 'AIR')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sslcommerzpaymentvalidatemodel',
            name='tran_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 7, 9, 1, 45, 546028, tzinfo=utc)),
        ),
    ]
