# Generated by Django 3.1.3 on 2020-12-07 09:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sslcommerz_payment', '0020_auto_20201207_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sslcommerzpaymentinitializationmodel',
            name='product_profile',
            field=models.CharField(choices=[('non-physical-goods', 'non-physical-goods'), ('travel-vertical', 'travel-vertical'), ('telecom-vertical', 'telecom-vertical'), ('airline-tickets', 'airline-tickets'), ('general', 'general'), ('physical-goods', 'physical-goods')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sslcommerzpaymentinitializationmodel',
            name='shipping_method',
            field=models.CharField(choices=[('NO', 'NO'), ('AIR', 'AIR'), ('TRUCK', 'TRUCK'), ('OTHERS', 'OTHERS'), ('SHIP', 'SHIP'), ('YES', 'YES'), ('COURIER', 'COURIER')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sslcommerzpaymentvalidatemodel',
            name='tran_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 7, 9, 11, 12, 17298, tzinfo=utc)),
        ),
    ]
