# Generated by Django 3.1.3 on 2020-12-28 09:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sslcommerz_payment', '0021_auto_20201207_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='sslcommerzpaymentinitializationmodel',
            name='customer_id',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='sslcommerzpaymentinitializationmodel',
            name='product_profile',
            field=models.CharField(choices=[('travel-vertical', 'travel-vertical'), ('general', 'general'), ('non-physical-goods', 'non-physical-goods'), ('telecom-vertical', 'telecom-vertical'), ('physical-goods', 'physical-goods'), ('airline-tickets', 'airline-tickets')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sslcommerzpaymentinitializationmodel',
            name='shipping_method',
            field=models.CharField(choices=[('COURIER', 'COURIER'), ('NO', 'NO'), ('AIR', 'AIR'), ('TRUCK', 'TRUCK'), ('OTHERS', 'OTHERS'), ('YES', 'YES'), ('SHIP', 'SHIP')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sslcommerzpaymentvalidatemodel',
            name='tran_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 28, 9, 34, 52, 853769, tzinfo=utc)),
        ),
    ]
