# Generated by Django 3.1.3 on 2021-01-03 11:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sslcommerz_payment', '0022_auto_20201228_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sslcommerzpaymentinitializationmodel',
            name='product_profile',
            field=models.CharField(choices=[('non-physical-goods', 'non-physical-goods'), ('travel-vertical', 'travel-vertical'), ('airline-tickets', 'airline-tickets'), ('general', 'general'), ('telecom-vertical', 'telecom-vertical'), ('physical-goods', 'physical-goods')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sslcommerzpaymentinitializationmodel',
            name='shipping_method',
            field=models.CharField(choices=[('OTHERS', 'OTHERS'), ('YES', 'YES'), ('NO', 'NO'), ('COURIER', 'COURIER'), ('AIR', 'AIR'), ('SHIP', 'SHIP'), ('TRUCK', 'TRUCK')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sslcommerzpaymentvalidatemodel',
            name='tran_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 3, 11, 27, 44, 805533, tzinfo=utc)),
        ),
    ]
